/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package halloqueensgambit.java;
import halloqueensgambit.java.Game.Move;
import halloqueensgambit.java.Game.Pos;
import java.io.IOException;

public class App {
    public String getGreeting(){
        return "a";
    }

    public void printNextGames(Game game){
        var lst = game.allNextGames();
        System.out.println("ALL NEXT GAME:");
        for (var g : lst){
            System.out.println();
            System.out.println(g);
        }
    }
    
    public static void main(String[] args) throws IOException {
        String fileName;
        if (args.length == 0){
            fileName = "initialGame.txt";
        } else {
            fileName = args[0];
        }
        Game game = new Game(fileName);
        System.out.println(game);
        System.out.println();
        System.out.println(FogartySolver.bestMove(game, 5));
//        new App().printNextGames(game);
//        System.out.println(new FogartySolver.moveRating(new Move(new Pos(1,1), new Pos(2,2)),2));
    }


    /*                                IO TO SCAN GAME FROM TXT FILES                               */
}
