/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package halloqueensgambit.java;

import java.io.IOException;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "a";
    }
//    public void twoPlayer(Game game) {
//        Game newGame = game;
//        // TODO: this is lazy
//        while (true) {
//            System.out.println(newGame);
//            newGame = IO.playerMove(newGame, new Scanner(System.in));
//        }
//    }

    public static void main(String[] args) throws IOException {
        String fileName;
        if (args.length == 0) {
            fileName = "/bestmove/a.txt";
        } else {
            fileName = args[0];
        }
        Game game = IO.readGameFromFile(fileName);
        System.out.println(game);

        Solver solver = new Solver(game);
        Scanner scanner = new Scanner(System.in);

        int depth = 5;
        while (depth > 0) {
            Solver.MoveRating bestMoveRating = solver.alphaBetaSearch(depth, Integer.MIN_VALUE, Integer.MAX_VALUE);
            System.out.println(bestMoveRating.move());
            System.out.println(bestMoveRating.rating());
            game.makeMove(bestMoveRating.move());
            System.out.println(game);
            depth--;
            String oppsMove = scanner.nextLine();
            game.makeMove(IO.scanMove(oppsMove));
        }





    }
}
