/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package halloqueensgambit.java;

import java.util.ArrayList;
import org.junit.jupiter.api.Test;

import halloqueensgambit.java.piece.Piece;

import java.util.Optional;
import static org.junit.jupiter.api.Assertions.*;

class MoveTesting {
    @Test void testUnMakeMove(){
        String fileName = "/bestmove/a.txt";
        Game game = IO.readGameFromFile(fileName);

        ArrayList<Move> moves = game.getLegalMoves();
        
        Game tmp = IO.readGameFromFile(fileName);
        assertEquals(game.getBoard(), tmp.getBoard());

        System.out.println(game);
        System.out.println(tmp);

        for(Move m: moves){
            Optional<Piece> captured = tmp.makeMove(m);
            tmp.unMakeMove(m, captured);
            System.out.println(m.start + " " + m.end + " ");
            assertEquals(game, tmp);
        }
    }
}